# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'PlantDoctorApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Firebase Pods
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'

  target 'PlantDoctorAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PlantDoctorAppUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
